# Generated by Django 5.2.1 on 2025-06-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('domicilio', 'Entrega a Domicilio'), ('retiro', 'Retiro en Tienda')], default='domicilio', max_length=20),
        ),
    ]
