# Generated by Django 5.2.1 on 2025-06-06 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVideo',
        ),
    ]
